Programm started at: 2025-07-14 02:00:57

Running in version 1.2[2025-07-14 23:32:32]
Git repositories synchronized
	

	NoneType: None


[2025-07-14 23:32:32]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-15 02:01:56

Running in version 1.2

[2025-07-15 12:17:12]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-07-15 16:53:19]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-07-15 23:32:34]
Git repositories synchronized
	

	NoneType: None


[2025-07-15 23:32:34]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-16 02:01:41

Running in version 1.2

[2025-07-16 23:32:16]
Git repositories synchronized
	

	NoneType: None


[2025-07-16 23:32:16]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-17 02:01:14

Running in version 1.2

[2025-07-17 23:32:49]
Git repositories synchronized
	

	NoneType: None


[2025-07-17 23:32:49]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-18 02:02:18

Running in version 1.2

[2025-07-18 14:34:36]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-07-18 23:32:54]
Git repositories synchronized
	

	NoneType: None


[2025-07-18 23:32:54]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-19 02:02:03

Running in version 1.2

[2025-07-19 17:57:26]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


