Programm started at: 2025-06-02 23:10:36

Running in version 1.1[2025-06-02 23:11:49]
Git repositories synchronized
	

	NoneType: None


[2025-06-02 23:11:49]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-02 23:20:57

Running in version 1.2

[2025-06-02 23:43:00]
Git repositories synchronized
	

	NoneType: None


[2025-06-02 23:43:00]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-03 01:41:13

Running in version 1.2

[2025-06-03 14:11:38]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-06-03 23:43:01]
Git repositories synchronized
	

	NoneType: None


[2025-06-03 23:43:01]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-04 01:41:02

Running in version 1.2

[2025-06-04 23:42:49]
Git repositories synchronized
	

	NoneType: None


[2025-06-04 23:42:49]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-05 01:40:38

Running in version 1.2

[2025-06-05 23:42:25]
Git repositories synchronized
	

	NoneType: None


[2025-06-05 23:42:25]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-06 01:41:13

Running in version 1.2

[2025-06-06 06:36:23]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-06-06 19:44:51]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-06-06 23:42:03]
Git repositories synchronized
	

	NoneType: None


[2025-06-06 23:42:03]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-07 01:41:05

Running in version 1.2

[2025-06-07 06:55:16]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-06-07 15:30:34]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-06-07 23:42:54]
Git repositories synchronized
	

	NoneType: None


[2025-06-07 23:42:54]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-08 01:40:45

Running in version 1.2

[2025-06-08 23:42:32]
Git repositories synchronized
	

	NoneType: None


[2025-06-08 23:42:32]
Terminating programm
	

	NoneType: None


