Programm started at: 2025-06-09 21:20:00

Running in version 1.2[2025-06-09 23:31:06]
Git repositories synchronized
	

	NoneType: None


[2025-06-09 23:31:06]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-10 01:41:04

Running in version 1.2

[2025-06-10 23:31:50]
Git repositories synchronized
	

	NoneType: None


[2025-06-10 23:31:50]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-11 01:40:42

Running in version 1.2

[2025-06-11 05:00:49]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-06-11 16:22:13]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


New initialisation demanded at: 2025-06-11 21:51:23

Running in version 1.2

[2025-06-11 23:31:28]
Git repositories synchronized
	

	NoneType: None


[2025-06-11 23:31:28]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-12 01:41:09

Running in version 1.2

[2025-06-12 23:31:56]
Git repositories synchronized
	

	NoneType: None


[2025-06-12 23:31:56]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-13 01:41:07

Running in version 1.2

[2025-06-13 23:31:53]
Git repositories synchronized
	

	NoneType: None


[2025-06-13 23:31:53]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-14 01:41:01

Running in version 1.2

[2025-06-14 23:31:47]
Git repositories synchronized
	

	NoneType: None


[2025-06-14 23:31:47]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-15 01:41:33

Running in version 1.2

[2025-06-15 20:20:10]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-06-15 20:34:12]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-06-15 23:31:22]
Git repositories synchronized
	

	NoneType: None


[2025-06-15 23:31:22]
Terminating programm
	

	NoneType: None


